cdata = {
	TWITCH2DCS_OPTIONS_TITLE = _('Twitch2DCS - A simple way to stay connected to your audience within DCS'),
	TWITCH2DCS_OPTIONS_VERSION = _('Version 1.1.3 / 2.5.5+'),
	TWITCH2DCS_ENABLE_TEXT = _('Enable'),
	TWITCH2DCS_USERNAME = _('Twitch Channel'),
	TWITCH2DCS_OAUTH = _('oAuthentication Token'),
	TWITCH2DCS_OAUTH_LINK = _('Get - https://twitchapps.com/tmi'),
	TWITCH2DCS_OAUTH_BUTTON = _('(Click To Get)'),
	TWITCH2DCS_HIDEINACTIVE = _('Hide Twitch2DCS when chat is inactive'),
	TWITCH2DCS_HIDEINACTIVETIMER = _('Inactive time in seconds'),
	TWITCH2DCS_FONTSIZE = _('Font Size'),
	TWITCH2DCS_LOCKUIPOSITION = _('Lock Overlay Position'),
	TWITCH2DCS_LOCKUICOMMENT = _('(Allows mouse functionality under window)'),
	TWITCH2DCS_SHOW_JOINPART = _('Show Joined/Left Messages'),
	TWITCH2DCS_DEBUG_MODE_TEXT = _('Debug Mode'),
	TWITCH2DCS_MODESHOTKEY = _('Hide/Show Hotkey'),
}